import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Default docs sidebar (from `docs/`)
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // New sidebar for Interview Experiences (from `interviews/`)
  interviewSidebar: [{ type: 'autogenerated', dirName: 'interviews' }],
};

export default sidebars;
