import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  interviewsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This will auto-generate from all files in interviews folder
    },
  ],
};

export default sidebars;
