name: Deploy Notes Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Docusaurus build artifacts
        uses: actions/cache@v4
        with:
          path: |
            .docusaurus
            build/.docusaurus
            node_modules/.cache
          key: docusaurus-${{ runner.os }}-${{ hashFiles('**/*.{md,mdx}', 'docusaurus.config.js', 'sidebars.js') }}
          restore-keys: |
            docusaurus-${{ runner.os }}-

      - name: Build with optimizations
        run: pnpm run build
        env:
          NODE_ENV: production
          NODE_OPTIONS: '--max-old-space-size=4096'
          # Docusaurus-specific optimizations
          DOCUSAURUS_FASTER_BUILD: true
          # Skip type checking during build (if applicable)
          TSC_COMPILE_ON_ERROR: true
          # Disable source maps in production
          GENERATE_SOURCEMAP: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
